name: Build & Deploy pipeline

on: [push]

env:
  MIX_ENV: test
  GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
  GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run_checks_and_deploly:
    name: Run quality checks & Deploy
    runs-on: ubuntu-latest
    environment: elixir-lab
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore cached deps
        id: cached-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Get & compile deps
        if: steps.cached-deps.outputs.cache-hit != 'true'
        run: mix deps.get && mix deps.compile
      - name: Save deps to cache
        if: steps.cached-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Restore cached application
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-
      - name: Compile application
        run: mix compile --warnings-as-errors
      - name: Save compiled application to cache
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-${{ github.sha }}
      - name: Check formatted
        run: mix format --check-formatted
      - name: Mix credo
        run: mix credo
      - name: Run docker-compose services
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            postgres
          up-flags: '--wait'
      - name: Mix test
        run: mix test
      - name: Push to Gigalixir
        run: |
          git remote add gigalixir https://$GIGALIXIR_USERNAME:$GIGALIXIR_API_KEY@git.gigalixir.com/elixir-lab.git
          git push -f gigalixir HEAD:refs/heads/main
