name: Build & Deploy pipeline

on: [push]

env:
  MIX_ENV: test

jobs:
  compilation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore cached deps
        id: cached-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Get & compile deps
        id: get-and-compile-deps
        if: steps.cached-deps.output.cache-hit != 'true'
        run: |
          MIX_ENV=${{ env.MIX_ENV }} mix deps.get
          MIX_ENV=${{ env.MIX_ENV }} mix deps.compile
      - name: Save deps to cache
        id: save-deps-cache
        if: steps.cached-deps.output.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Restore cached application
        id: cached-application
        uses: actions/cache/restore@v4
        with:
          path: _build/${{ env.MIX_ENV }}/lib/elixir_lab
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}-application-code
      - name: Compile application
        id: compile-application
        run: MIX_ENV=${{ env.MIX_ENV }} mix compile
      - name: Save compiled application to cache
        id: cache-compiled-application
        if: steps.cached-deps.output.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: _build/${{ env.MIX_ENV }}/lib/elixir_lab
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}-application-code

