name: Build & Deploy pipeline

on: [push]

env:
  MIX_ENV: test

jobs:
  compilation:
    name: Deps & App compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore cached deps
        id: cached-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Get & compile deps
        id: get-and-compile-deps
        if: steps.cached-deps.outputs.cache-hit != 'true'
        run: |
          MIX_ENV=${{ env.MIX_ENV }} mix deps.get
          MIX_ENV=${{ env.MIX_ENV }} mix deps.compile
      - name: Save deps to cache
        id: save-deps-cache
        if: steps.cached-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Restore cached application
        id: cached-application
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-
      - name: Compile application
        id: compile-application
        run: MIX_ENV=${{ env.MIX_ENV }} mix compile --warnings-as-errors
      - name: Save compiled application to cache
        id: cache-compiled-application
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-${{ github.sha }}
  test:
    name: Test suite
    runs-on: ubuntu-latest
    needs: 
      - compilation
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore cached application
        id: cached-application
        uses: actions/cache/restore@v4
        with:
          path: |
            deps/
            _build/
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-

      - name: Mix test
        id: mix-test
        run: MIX_ENV=${{ env.MIX_ENV }} mix test

