name: Build & Deploy pipeline

on: [push]

env:
  MIX_ENV: test

jobs:
  run_checks_and_deploly:
    name: Run quality checks & Deploy
    runs-on: ubuntu-latest
    environment: elixir-lab
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        id: setup-beam
        with:
          version-file: .tool-versions
          version-type: strict
      - name: Restore cached deps
        id: cached-deps
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Get & compile deps
        id: get-and-compile-deps
        if: steps.cached-deps.outputs.cache-hit != 'true'
        run: |
          MIX_ENV=${{ env.MIX_ENV }} mix deps.get
          MIX_ENV=${{ env.MIX_ENV }} mix deps.compile
      - name: Save deps to cache
        id: save-deps-cache
        if: steps.cached-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-mix-lock-${{ hashFiles('mix.lock') }}
      - name: Restore cached application
        id: cached-application
        uses: actions/cache/restore@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-
      - name: Compile application
        id: compile-application
        run: MIX_ENV=${{ env.MIX_ENV }} mix compile --warnings-as-errors
      - name: Save compiled application to cache
        id: cache-compiled-application
        uses: actions/cache/save@v4
        with:
          path: |
            deps
            _build
          key: elixir-${{ steps.setup-beam.outputs.elixir-version }}-OTP-${{ steps.setup-beam.outputs.otp-version }}-application-code-${{ github.sha }}
      - name: Check formatted
        id: check-formatted
        run: MIX_ENV=${{ env.MIX_ENV }} mix format --check-formatted
      - name: Mix credo
        id: mix-credo
        run: MIX_ENV=${{ env.MIX_ENV }} mix credo
      - name: Run docker-compose services
        uses: hoverkraft-tech/compose-action@v2.4.1
        with:
          compose-file: "./docker-compose.yaml"
          services: |
            postgres
          up-flags: '--wait'
      - name: Mix test
        id: mix-test
        run: MIX_ENV=${{ env.MIX_ENV }} mix test
      - name: Push to Gigalixir
        run: |
          git remote add gigalixir https://$GIGALIXIR_USERNAME:$GIGALIXIR_API_KEY@git.gigalixir.com/elixir-lab.git
          git push -f gigalixir HEAD:refs/heads/main
        env: 
          GIGALIXIR_USERNAME: ${{ secrets.GIGALIXIR_USERNAME }}
          GIGALIXIR_API_KEY: ${{ secrets.GIGALIXIR_API_KEY }}
